---> 01. USING EXISTING DATABASE

USE DATABASE DEV_COMPUTE_DB;


---> 02. CREATE AN EMPTY TABLE

CREATE OR REPLACE TABLE DEV_COMPUTE_DB.PUBLIC_ORG.MENU
(
    menu_id NUMBER(19,0),
    menu_type_id NUMBER(38,0),
    menu_type VARCHAR(16777216),
    truck_brand_name VARCHAR(16777216),
    menu_item_id NUMBER(38,0),
    menu_item_name VARCHAR(16777216),
    item_category VARCHAR(16777216),
    item_subcategory VARCHAR(16777216),
    cost_of_goods_usd NUMBER(38,4),
    sale_price_usd NUMBER(38,4),
    menu_item_health_metrics_obj VARIANT
);


---> 03. CREATE INTEGRATION OBJECT FOR EXTERNAL STAGE

CREATE STORAGE INTEGRATION AZURE_INTEGRT
    TYPE = EXTERNAL_STAGE
    STORAGE_PROVIDER = AZURE
    ENABLED = TRUE
    AZURE_TENANT_ID = '2769098133-tf765-869494'
    STORAGE_ALLOWED_LOACTIONS = ('azure://snowflakedemo.blob.core.windows.net/curated/dev_files/', 'azure://snowflakedemo.blob.core.windows.net/curated/dev_files_schema/');


---> 04. DESCRIBE INTEGRATION OBJECTS TO AUTHORIZE SNOWFLAKE TO READ DATA FROM AZURE STORAGE

DESCRIBE STORAGE AZURE_INTEGRT


---> 05. CREATE FILE FORMAT TO INFORM SNOWFLAKE WHICH TYPE OF FILE NEED TO INGEST

CREATE OR REPLACE FILE FORMAT DEV_COMPUTE_DB.PUBLIC_ORG.BLOB_CSV_FORMAT
TYPE = CSV FIELD_DELIMITER = ',' SKIP_HEADER = 1;


---> 06. CREATE STAGE OBJECT TO LET SNOWFLAKE KNOW FROM WHERE TO PICK UP THE FILES

CREATE OR REPLACE STAGE DEV_COMPUTE_DB.PUBLIC_ORG.AZURE_FLIE_STAGE
STORAGE_INTEGRATION = AZURE_INTEGRT
URL = 'azure://snowflakedemo.blob.core.windows.net/curated/dev_files/menu.csv'
FILE_FORMAT = BLOB_CSV_FORMAT;


---> 07. NOW LOOK AT THE DATA OF THE STAGE OBJECTS

SELECT $1, $2, $3 
FROM @DEV_COMPUTE_DB.PUBLIC_ORG.AZURE_FLIE_STAGE;


---> 08. LOAD THE DATA FROM STAGE TO THE TABLE

COPY INTO DEV_COMPUTE_DB.PUBLIC_ORG.MENU
FROM @DEV_COMPUTE_DB.PUBLIC_ORG.AZURE_FLIE_STAGE;































