CREATE DATABASE FALCON_SALES_DB;

--- // First create 3 different schema

CREATE OR REPLACE SCHEMA FALCON_SALES_DB.STAGGING_ZONE;
CREATE OR REPLACE SCHEMA FALCON_SALES_DB.CURATED_ZONE;
CREATE OR REPLACE SCHEMA FALCON_SALES_DB.ANALYTICAL_ZONE;


--- // Create tables in STAGGING_ZONE

CREATE OR REPLACE TRANSIENT TABLE FALCON_SALES_DB.STAGGING_ZONE.CUSTOMER_STG
(
    CUSTOMER_CODE VARCHAR,
    CUSTOMER_NAME VARCHAR,
    CUSTOMER_TYPE VARCHAR
    
) COMMENT = "CUSTOMER_STG is created in STAGGING_ZONE";


CREATE OR REPLACE TRANSIENT TABLE FALCON_SALES_DB.STAGGING_ZONE.PRODUCT_STG
(
    PRODUCT_CODE VARCHAR,
    PRODUCT_TYPE VARCHAR
    
)COMMENT = "PRODUCT_STG is created in STAGGING_ZONE";


CREATE OR REPLACE TRANSIENT TABLE FALCON_SALES_DB.STAGGING_ZONE.MARKET_STG
(
    MARKET_CODE VARCHAR,
    MARKET_NAME VARCHAR,
    ZONE VARCHAR
) COMMENT = "PRODUCT_STG is created in STAGGING_ZONE";


--- // Create a file format for file load

CREATE OR REPLACE FILE FORMAT FALCON_SALES_DB.STAGGING_ZONE.csv_loader
    type = 'csv'
    compression = 'auto'
    field_delimiter = ','
    skip_header = 1;
    

--- // Check Data Loads

SELECT * FROM FALCON_SALES_DB.STAGGING_ZONE.PRODUCT_STG;
SELECT * FROM FALCON_SALES_DB.STAGGING_ZONE.CUSTOMER_STG;
SELECT * FROM FALCON_SALES_DB.STAGGING_ZONE.MARKET_STG;

-- TRUNCATE TABLE FALCON_SALES_DB.STAGGING_ZONE.CUSTOMER_STG;













