USE SCHEMA FALCON_SALES_DB.CURATED_ZONE;


--- Create Task Object at Curated Zone.
--- // Create Task object for CUSTOMER_CURATED table.

CREATE OR REPLACE TASK FALCON_SALES_DB.CURATED_ZONE.CURATED_CUSTOMER_TSK
    WAREHOUSE = 'COMPUTE_WH'
    schedule = '10 seconds'
when
    system$stream_has_data('FALCON_SALES_DB.STAGGING_ZONE.stagging_customer_stream')
as
    merge into FALCON_SALES_DB.CURATED_ZONE.CUSTOMER_CURATED as C
    Using FALCON_SALES_DB.STAGGING_ZONE.stagging_customer_stream as S on

    C.CUSTOMER_CODE = S.CUSTOMER_CODE AND 
    C.CUSTOMER_NAME = S.CUSTOMER_NAME
    
WHEN MATCHED
    THEN UPDATE SET
    C.CUSTOMER_CODE = S.CUSTOMER_CODE,
    C.CUSTOMER_NAME = S.CUSTOMER_NAME,
    C.CUSTOMER_TYPE = S.CUSTOMER_TYPE
WHEN NOT MATCHED THEN
INSERT 
(CUSTOMER_CODE, CUSTOMER_NAME, CUSTOMER_TYPE)
VALUES
(
    S.CUSTOMER_CODE,
    S.CUSTOMER_NAME,
    S.CUSTOMER_TYPE
);

--- // Create Task object for MARKET_CURATED table.

CREATE OR REPLACE TASK FALCON_SALES_DB.CURATED_ZONE.CURATED_MARKET_TSK
    warehouse = 'COMPUTE_WH'
    schedule = '2 minute'
WHEN
    system$stream_has_data('FALCON_SALES_DB.STAGGING_ZONE.stagging_market_stream')
as
    MERGE INTO FALCON_SALES_DB.CURATED_ZONE.MARKET_CURATED as M
    USING FALCON_SALES_DB.STAGGING_ZONE.stagging_market_stream S ON
    M.MARKET_CODE = S.MARKET_CODE AND
    M.MARKET_NAME = S.MARKET_NAME
    
WHEN MATCHED
    THEN UPDATE SET
    M.MARKET_CODE = S.MARKET_CODE, 
    M.MARKET_NAME = S.MARKET_NAME,
    M.ZONE = S.ZONE
    
WHEN NOT MATCHED THEN
INSERT (MARKET_CODE, MARKET_NAME, ZONE)
VALUES
(
    S.MARKET_CODE,
    S.MARKET_NAME,
    S.ZONE
);


--- // Create Task object for PRODUCT_CURATED table.


CREATE OR REPLACE TASK FALCON_SALES_DB.CURATED_ZONE.CURATED_PRODUCT_TSK
    warehouse = 'COMPUTE_WH'
    schedule = '3 minute'
WHEN
    system$stream_has_data('FALCON_SALES_DB.STAGGING_ZONE.stagging_product_stream')
as
    MERGE INTO FALCON_SALES_DB.CURATED_ZONE.PRODUCT_CURATED AS P
    USING FALCON_SALES_DB.STAGGING_ZONE.stagging_product_stream AS S ON
    P.PRODUCT_CODE = S.PRODUCT_CODE
WHEN MATCHED 
    THEN UPDATE SET
    P.PRODUCT_CODE = S.PRODUCT_CODE,
    P.PRODUCT_TYPE = S.PRODUCT_TYPE
    
WHEN NOT MATCHED THEN
    INSERT (PRODUCT_CODE, PRODUCT_TYPE)
    VALUES
    (
        S.PRODUCT_CODE,
        S.PRODUCT_TYPE
    );



SHOW TASKS;


// *** Lets Resume All created task. ***


ALTER TASK FALCON_SALES_DB.CURATED_ZONE.CURATED_CUSTOMER_TSK RESUME;

-- // Check Data Load in TASK object

SELECT * FROM FALCON_SALES_DB.CURATED_ZONE.CURATED_CUSTOMER_TSK;


SELECT * FROM FALCON_SALES_DB.CURATED_ZONE.CUSTOMER_CURATED;















    




















    








    
   